server:
  port: 8484
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: automomo-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost
